export const allBooks = [
  "The Odyssey",
  "Harry Potter",
  "Romeo & Juliet",
  "Twilight",
  "Hunger Games",
  "MacBeth",
  "Cinderella",
  "Sleeping Beauty",
  "The Great Gatsby",
  "A Game of Thrones",
  "Lord of the Rings",
  "Hamlet",
  "A Tale of Two Cities",
  "War and Peace",
  "Pride and Prejudice",
  "Great Expectations",
  "Sense and Sensibility",
  "1984",
  "A Condederacy of Dunces",
  "The Adventures of Tom Sawyer",
  "The Alchemist",
  "Alice's Adventures in Wonderland",
  "And Then There Were None",
  "Anne of Green Gables",
  "The Chronicles of Narnia",
  "The Da Vinci Code",
  "Fifty Shades of Grey",
  "Dracula",
  "Flowers in the Attic",
  "Frankenstein",
  "Beloved",
  "The Book Thief",
  "The Call of the Wild",
  "The Catcher in the Rye",
  "Charlotte's Web",
  "Gone Girl",
  "The Help",
  "The Notebook",
  "The Outsiders",
  "The Picture of Dorian Gray",
  "Rebecca",
  "The Hitchhiker's Guide to the Galaxy",
  "Jane Eyre",
  "Little Women",
  "Their Eyes Were Watching God",
  "To Kill a Mockingbird",
  "Moby-Dick",
  "Wuthering Heights",
  "The Martian",
  "Memoirs of a Geisha",
  "Lonesome Dove",
  "Dune",
  "The Hunchback of Notre Dame",
  "The Jungle Book",
  "Pocahontas",
  "Les Miserables",
  "Phantom of the Opera",
  "The Three Muskateers",
  "Sherlock Holmes",
  "The Tempest",
  "Julius Caesar",
  "Richard III",
  "Hansel and Gretel",
  "Bluebeard",
  "Matilda",
  "The Handmaid's Tale",
  "Goosebumps",
  "The Legend of Sleepy Hollow",
  "Emma",
  "The Scarlet Letter",
  "A Christmas Carol",
  "The Strange Case of Dr. Jekyll and Mr. Hyde",
  "Treasure Island",
  "The Importance of Being Earnest",
  "Peter Pan",
  "The Crucible",
  "Beowulf",
  "The Canterbury Tales",
  "A Little Princess",
  "Around the World in Eighty Days",
  "The War of the Worlds",
  "Inferno",
  "Vanity Fair",
  "The Princess Bride",
  "The Prince & the Pauper",
  "The Arabian Nights",
  "The Life of Pi",
  "A Series of Unfortunate Events",
  "Roald Dahl's The Witches",
  "The Collected Works of Edgar Allan Poe",
  "Percy Jackson and the Lightning Thief",
  "The Iliad",
  "The Prince",
  "The Art of War",
  "The Once and Future King",
  "The Grinch",
  "The Time Machine",
  "The X-Men",
  "The Secret Garden",
  "Madame Bovary",
  "One Flew Over the Cuckoo's Nest",
]

export const allMovies = [
  "Star Wars: A New Hope",
  "Labrynth",
  "The Mummy",
  "Notting Hill",
  "The Godfather",
  "Casablanca",
  "Gone with the Wind",
  "The Wizard of Oz",
  "Psycho",
  "Forrest Gump",
  "The Sound of Music",
  "Star Wars: The Empire Strikes Back",
  "2001: A Space Odyssey",
  "E.T. the Extra-Terrestrial",
  "Hocus Pocus",
  "Silence of the Lambs",
  "Chinatown",
  "It's a Wonderful Life",
  "Dr. Strangelove",
  "Some Like It Hot",
  "Breakfast at Tiffany's",
  "Apocalypse Now",
  "Amadeus",
  "Gladiator",
  "Titanic",
  "Raiders of the Lost Arc",
  "Rocky",
  "Wicked",
  "Grease",
  "My Fair Lady",
  "Jaws",
  "The Good, the Bad, and the Ugly",
  "Braveheart",
  "Roman Holiday",
  "Jurassic Park",
  "The Exorcist",
  "Goodfellas",
  "Bonnie and Clyde",
  "The Shining",
  "It Happened One Night",
  "Mr. Smith Goes to Washington",
  "Fargo",
  "The Grapes of Wrath",
  "Close Encounters of the Third Kind",
  "Pulp Fiction",
  "Murder on the Orient Express",
  "The 39 Steps",
  "Reberl Without a Cause",
  "Citizen Kane",
  "King Kong",
  "Godzilla",
  "The Little Mermaid",
  "Beauty and the Beast",
  "Tootsie",
  "Big",
  "Mad Max",
  "Wall-E",
  "Lost in Translation",
  "Finding Nemo",
  "Aladdin",
  "Pocahontas",
  "Scooby-Doo",
  "Mad Men",
  "Breaking Bad",
  "Doctor Who",
  "Stranger Things",
  "Gravity Falls",
  "Sex and the City",
  "The Twilight Zone",
  "Pretty Little Liars",
  "The Office",
  "Hercules",
  "Clueless",
  "A Knight's Tale",
  "Fast & Furious",
  "Avatar the Last Airbender",
  "Twin Peaks",
  "The Avengers",
  "The Incredibles",
  "Frozen",
  "Wonder Woman",
  "Skyfall",
  "Dr. No",
  "Live and Let Die",
  "From Russia with Love",
  "Transformers",
  "Mission Impossible",
  "Guardians of the Galaxy",
  "The Matrix",
  "The Magnificent Seven",
  "The Creature from the Black Lagoon",
  "High School Musical",
  "You've Got Mail",
  "Sleepless in Seattle",
  "John Wick",
  "Weekend at Bernie's",
  "The Breakfast Club",
  "Home Alone",
  "Parks & Recreation",
  "Men in Black",
  "Home Alone 2: Lost in New York",
]

export const allCharacters = [
  "A lovelorn teenager",
  "A down-on-their luck detective",
  "An heir(ess) who just lost their family's entire fortune",
  "A housekeeper for an enormously wealthy family",
  "A school teacher",
  "A nanny",
  "A secretary",
  "An aspiring author",
  "A long-lost member of a royal family",
  "A secret wizard/witch",
  "An escaped convict",
  "A bored office worker",
  "An aspiring artist",
  "A failed artist turned art thief",
  "A college drop out",
  "An undercover spy",
  "A runaway orphan",
  "A coffee shop barista",
  "An exiled knight",
  "An assistant to a Very Important Person",
  "The best friend of a super hero",
  "A professor",
  "A group of 12-year-old mystery solvers",
  "A beat cop",
  "A ballet dancer",
  "A 26-year-old computer programmer",
  "A retired FBI agent",
  "A group of misfit teenagers",
  "A PhD student obsessed with their work",
  "A paleantologist",
  "An herbologist",
  "A lonely librarian",
  "A cryptozoologist",
  "A cat-lover",
  "A professional dog walker",
  "a magician",
  "A florist",
  "A baker",
  "A house-wife",
  "An Elvis impersonator",
  "A professional clown",
  "A professional gambler",
  "A poor apprentice",
  'A member of a "Worst Books of History" book club',
  "A book store employee",
  "A cat burglar",
  "A palm-reader",
  "A bartender with dreams of owning their own place",
  "The forever-Side Kick",
  "A future ruler",
]

export const allEvents = [
  "discovers the entrance to a secret world",
  "decides to rob a bank",
  "is invited to join a secret society",
  "happens upon a murder",
  "plans a rebellion",
  "plots to steal a throne",
  "is dared to enter a (reportedly) haunted mansion",
  "is told they've just inherited a fortune",
  "finds a long-lost painting",
  "discovers their doppleganger",
  "falls in love with their worst enemy",
  "reluctantly falls in love",
  "decides they'll marry the next person they see",
  "needs to fake a romance to appease their family",
  "decides to overthrow the current power structure",
  "happens upon a job as a companion to an eccentric recluse",
  "discovers their new pocket watch is actually a time machine",
  "is haunted by the ghost of a murder victim",
  "aims to reinvent themselves",
  "is sent on a quest to find a magical sword",
  "is pretty sure they just went on a date with the Grim Reaper",
  "discovers a secret book of magic",
  "discovers a 60 year-old unsent love note",
  "uncovers a spy ring",
  "hatches a dragon egg",
  "finds a treasure map",
  "must rescue a loved one",
  "pursues a runaway criminal",
  "is hunted by a monster",
  "inadvertantly joins a rebellion",
  "gains super powers",
  "infiltrates an evil organiztion",
  "happens upon bigfoot",
  "befriends a stray cat who seems to predict the future",
  "gets married",
  "becomes a detective",
  "starts a new job",
  "quits their job",
  "makes an unusual friend",
  "makes an unsuccessful proposal",
  "befriends a wizard",
  "is told by a drunk person at a party that they're The Chosen One",
  "discovers ancient ruins",
  "meets an all-powerful toad",
  "runs away to",
  "joins a group of cat burglars",
  "suddenly gains psychic powers",
  "gets lost in a magical labrynth",
  "thinks they just saw a unicorn",
  "buys a falling-down, possibly haunted house",
]

export const allPlaceSpecifiers = [
  "in 1920s",
  "in 1942",
  "in acoffee shop in modern-day",
  "at a secret museum in",
  "at a nightclub in 1980",
  "at a boarding school in 1890s",
  "in medieval",
  "in 1950s",
  "in ancient",
  "in a near-future version of",
  "in a magical version of 1870s",
  "in the late 1700s",
  "in Victorian",
  "in Edwardian",
  "aboard a pirate ship leaving",
  "in a magical version of modern day",
  "in a magical version of",
  "in a steampunk version of",
  "in a fantasy land inspired by",
  "in 1930s",
  "in a tavern in",
  "in a set of tunnels hidden underneath",
  "in a fantasy version of ancient",
  "in a dragon-habitated version of",
  "in an undersea version of",
  "in an outerspace version of",
  "in a dystopian version of",
  "in a cyberpunk version of",
  "in a tea shop in",
  "in a bookstore in",
  "at or near a traveling carnaval",
  "at or near a flea market in",
  "in a zeplin above",
  "in the wilderness outside of",
  "in 1960s",
  "in a zombie-plagued version of",
  "at a big sporting event in",
  "during the biggest festival of the year in",
  "at the oldest cemetery in",
  "at the biggest party of the year in",
  "on a holiday to",
  "on public transportation in",
  "in a society inspired by a mix between Ancient Egypt and modern",
  "in a society inspired by a mix between Ancient China and modern",
  "in a society inspired by a mix between Ancient Rome and modern",
  "in a society inspired by a mix between Celtic Britain and modern",
  "in a ghost-infested version of",
  "in the most boring version of",
  "in the city park in",
  "at an arcade in",
]

export const allPlaces = [
  "Kansas",
  "Paris",
  "London",
  "France",
  "Paris",
  "Tokyo",
  "Miami",
  "Brazil",
  "Russia",
  "Italy",
  "German",
  "Hawaii",
  "New York",
  "Chicago",
  "New Orleans",
  "Los Angeles",
  "Alaska",
  "Antartica",
  "Nepal",
  "Hong Kong",
  "Mumbai",
  "Mexico",
  "Barcelona",
  "Morocco",
  "Rome",
  "South Africa",
  "Egypt",
  "Greece",
  "Sweden",
  "Jordan",
  "Mongolia",
  "Amsterdam",
  "Seattle",
  "Singapore",
  "Canada",
  "Argentina",
  "South Korea",
  "Madagascar",
  "Norway",
  "Scotland",
  "Ireland",
  "Florida",
  "Switzerland",
  "Austria",
  "Prague",
  "Australia",
  "San Francisco",
  "Boston",
  "Brussels",
  "Nashville",
]
